CREATE TABLE IF NOT EXISTS ratings (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);
CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description varchar(255),
    release_date date,
    duration INTEGER,
    rating_id INTEGER REFERENCES ratings (rating_id)
);
CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER REFERENCES films (id),
    genre_id INTEGER REFERENCES genres (genre_id)
);
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    email varchar(255),
    login varchar(255),
    birthday date
);
CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS status (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);
CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    status_id INTEGER REFERENCES status (status_id)
);
